[project]
name = "ml-fundamentals"
version = "0.1.0"
description = "Machine-learning models implemented from first principles"
readme = "README.md"
authors = [
    { name = "Vivek Ravi", email = "65517839+vivek-r-ravi@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.4.3",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
